FROM mariadb:11.2

RUN apt-get update && \
    apt-get install -y mariadb-client && \
    rm -rf /var/lib/apt/lists/* \
    && apt-get install -y --no-install-recommends net-tools \
    && apt-get install -y --no-install-recommends iputils-ping \
